extends RefCounted

## Parser for WaveLoopManager `.sli` sidecars (docs/sli_loop.md).
##
## Format (all files shipped with this game use the simple form):
##
##   #2.00
##   # Sound Loop Information (utf-8)
##   # Generated by WaveLoopManager.cpp
##   Link { From=4917760;  To=1268096;  Smooth=False; Condition=eq;
##          RefValue=0;   CondVar=0;  }
##   Label { Position=3080192; Name='sabi'; }
##
## `From`/`To` are PCM sample positions in the companion ogg; `Condition=eq`
## compares CondVar against RefValue. Every shipped file declares
## `CondVar=0; RefValue=0`, i.e. an unconditional loop, so the runtime applies
## the loop whenever a Link exists and records a warning for anything else.

const SAMPLE_RATE_FALLBACK := 44100.0

var loops: Array[Dictionary] = []
var labels: Array[Dictionary] = []
var parse_notes: Array[String] = []


## Load a `.sli` sidecar for the given audio path. The original package keeps
## them beside the ogg (assets/bgm/…); accept an explicit override directory so
## callers can point at the restored tree as well.
func load_for_audio(audio_path: String, override_dir: String = "") -> bool:
	loops.clear()
	labels.clear()
	parse_notes.clear()
	var stem := audio_path.get_file().get_basename()
	if audio_path.to_lower().ends_with(".ogg"):
		stem = audio_path.get_file().substr(0, audio_path.get_file().length() - 4)
	for candidate in _candidate_paths(audio_path, stem, override_dir):
		if not FileAccess.file_exists(candidate):
			continue
		var file := FileAccess.open(candidate, FileAccess.READ)
		if file == null:
			continue
		parse(file.get_as_text())
		if not loops.is_empty():
			return true
	return false


func _candidate_paths(audio_path: String, stem: String, override_dir: String) -> Array[String]:
	var paths: Array[String] = []
	if override_dir != "":
		paths.append(override_dir.path_join(stem + ".ogg.sli"))
	paths.append(audio_path + ".sli")
	# Absolute form for res:// URIs, and the original-package location which is
	# where every shipped sidecar actually lives.
	paths.append(ProjectSettings.globalize_path(audio_path) + ".sli")
	var dir := audio_path.get_base_dir()
	paths.append(dir.path_join(stem + ".ogg.sli"))
	paths.append(dir.path_join(stem + ".sli"))
	paths.append("res://assets/bgm/" + stem + ".ogg.sli")
	return paths


func parse(text: String) -> void:
	loops.clear()
	labels.clear()
	for match in _find_blocks(text, "Link"):
		var body := match
		var link := {
			"from": _int_field(body, "From"),
			"to": _int_field(body, "To"),
			"smooth": _bool_field(body, "Smooth"),
			"condition": _word_field(body, "Condition"),
			"cond_var": _word_field(body, "CondVar"),
			"ref_value": _word_field(body, "RefValue"),
		}
		if int(link["from"]) <= 0 or int(link["to"]) <= 0:
			parse_notes.append("Link with non-positive sample position skipped")
			continue
		loops.append(link)
	for match in _find_blocks(text, "Label"):
		labels.append({
			"position": _int_field(match, "Position"),
			"name": _quoted_field(match, "Name"),
		})


## True when this Link should apply to the current playback. Only the
## unconditional form (Condition=eq with CondVar == RefValue) is supported;
## anything else is warned about and treated as inactive.
func loop_applies(link: Dictionary) -> bool:
	var condition := str(link.get("condition", "")).to_lower()
	if condition == "" or condition == "no" or condition == "none":
		return true
	if condition == "eq":
		return str(link.get("cond_var", "0")) == str(link.get("ref_value", "0"))
	parse_notes.append("unsupported loop condition: " + condition)
	return false


## First applicable loop as (begin_seconds, end_seconds), or {} when none.
func loop_seconds(sample_rate: float = SAMPLE_RATE_FALLBACK) -> Dictionary:
	# WaveLoopManager semantics: play through to `From`, then jump back to `To`
	# — so the repeating range is [To, From]. The loop-ready copy is truncated
	# at `From`, which makes Godot's loop_offset express exactly that range.
	var rate := sample_rate if sample_rate > 0.0 else SAMPLE_RATE_FALLBACK
	for link in loops:
		if not loop_applies(link):
			continue
		return {
			"begin": float(link["to"]) / rate,
			"end": float(link["from"]) / rate,
			"smooth": bool(link.get("smooth", false)),
		}
	return {}


# --- field scraping --------------------------------------------------------

func _find_blocks(text: String, kind: String) -> Array[String]:
	var out: Array[String] = []
	var pattern := RegEx.create_from_string(kind + "\\s*\\{([^}]*)\\}")
	for line in text.split("\n"):
		var found := pattern.search(line)
		if found != null:
			out.append(found.get_string(1))
	return out


func _int_field(body: String, name: String) -> int:
	var found := RegEx.create_from_string(name + "\\s*=\\s*(-?[0-9]+)").search(body)
	return int(found.get_string(1)) if found != null else 0


func _word_field(body: String, name: String) -> String:
	var found := RegEx.create_from_string(name + "\\s*=\\s*([A-Za-z0-9_]+)").search(body)
	return found.get_string(1) if found != null else ""


func _quoted_field(body: String, name: String) -> String:
	var found := RegEx.create_from_string(name + "\\s*=\\s*'([^']*)'").search(body)
	return found.get_string(1) if found != null else ""


func _bool_field(body: String, name: String) -> bool:
	var found := RegEx.create_from_string(name + "\\s*=\\s*([A-Za-z]+)").search(body)
	return found != null and found.get_string(1).to_lower() == "true"
