#!/usr/bin/env python3
"""Compile the Kirikiri branch-flag expansion table into runtime JSON.

Input:  assets/main/scnchartdata.tjs (UTF-16LE, auto-generated by the original
        game's chart tooling).
Output: assets/ui/compiled/branch_flags.json, consumed by
        scripts/story/branch_flags.gd at story start.

The TJS file is parsed structurally but narrowly: only the `"flags" => %[ ... ]`
and `"branches" => [ ... ]` sections are extracted, using balanced-bracket
scanning (no full TJS parser). Unknown syntax fails loudly instead of silently
dropping entries, per docs/plan/PLAN_P0_BRANCH_ENGINE.md step 1.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/main/scnchartdata.tjs"
OUTPUT = ROOT / "assets/ui/compiled/branch_flags.json"
EXPECTED_BRANCH_COUNT = 7  # reconciliation anchor per PLAN_P0 step 1


def read_utf16(path: Path) -> str:
    data = path.read_bytes()
    if data[:2] == b"\xff\xfe":
        return data[2:].decode("utf-16-le")
    if data[:2] == b"\xfe\xff":
        return data[2:].decode("utf-16-be")
    return data.decode("utf-8")


def scan_balanced(text: str, open_index: int) -> tuple[int, int]:
    """Given the index of an opening '[' or '%[', return (content_start,
    content_end) of the balanced bracket body. Bracket depth counting ignores
    quoted strings; '%' immediately before '[' is a TJS literal marker."""
    assert text[open_index] == "[", "open_index must point at '['"
    depth = 0
    i = open_index
    in_string = False
    n = len(text)
    while i < n:
        ch = text[i]
        if in_string:
            if ch == '"':
                in_string = False
        elif ch == '"':
            in_string = True
        elif ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                return open_index + 1, i
        i += 1
    raise ValueError("unbalanced brackets starting at offset %d" % open_index)


def find_map_section(text: str, key: str) -> str:
    """Locate `"key" => (const) %[` or `"key" => (const) [` and return the
    balanced bracket body text (the TJS literal marker `%` is optional)."""
    marker = '"%s" => (const)' % key
    pos = text.find(marker)
    if pos < 0:
        raise ValueError("section %r not found in source" % key)
    open_index = text.index("[", pos + len(marker))
    start, end = scan_balanced(text, open_index)
    return text[start:end]


def parse_flags(section: str) -> dict:
    """Parse `name => [[tag, value, weight], ...]` entries. Some names may
    carry multiple triples, so each key's balanced body is scanned for every
    `[tag, value, weight]` triple instead of assuming exactly one."""
    flags: dict[str, list] = {}
    key_iter = list(re.finditer(r'"([A-Za-z0-9_]+)"\s*=>\s*\(const\)\s*\[', section))
    if not key_iter:
        raise ValueError("no flag entries parsed — source layout changed?")
    for index, match in enumerate(key_iter):
        name = match.group(1)
        open_index = section.index("[", match.end() - 1)
        start, end = scan_balanced(section, open_index)
        body = section[start:end]
        triples = re.findall(r'\[\s*"([^"]+)"\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\]', body)
        if not triples:
            raise ValueError("flag %r has no [tag, value, weight] triple" % name)
        flags[name] = [[tag, int(value), int(weight)] for tag, value, weight in triples]
        if index + 1 < len(key_iter):
            next_start = key_iter[index + 1].start()
            stripped = section[end:next_start].strip()
            # After each key body comes its own closing ']' plus a ',' separator.
            if stripped not in (",", "],"):
                raise ValueError(
                    "unexpected syntax between flag %r and %r: %r"
                    % (name, key_iter[index + 1].group(1), stripped[:40])
                )
    return flags


def parse_branches(section: str) -> list:
    return re.findall(r'"([^"]+)"', section)


def main() -> int:
    if not SOURCE.exists():
        print("FAIL: source missing: %s" % SOURCE, file=sys.stderr)
        return 1
    text = read_utf16(SOURCE)
    flags = parse_flags(find_map_section(text, "flags"))
    branches = parse_branches(find_map_section(text, "branches"))
    if len(branches) != EXPECTED_BRANCH_COUNT:
        print(
            "FAIL: branches reconciliation mismatch: expected %d, parsed %d"
            % (EXPECTED_BRANCH_COUNT, len(branches)),
            file=sys.stderr,
        )
        return 1
    entry_count = sum(len(v) for v in flags.values())
    report = {
        "format": "tenshin-branch-flags-v1",
        "source": "assets/main/scnchartdata.tjs",
        "branches": branches,
        "flags": flags,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(report, ensure_ascii=False, indent="\t"), encoding="utf-8")
    print(
        "OK: %d flag names / %d triples / %d branch nodes -> %s"
        % (len(flags), entry_count, len(branches), OUTPUT)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
